# Generated by Django 6.0.6 on 2026-06-12 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(choices=[('agentic_rag', 'Agentic RAG'), ('naive_rag', 'Naive RAG'), ('no_rag', 'No RAG Baseline')], default='agentic_rag', max_length=20)),
                ('llm_model', models.CharField(max_length=100)),
                ('notes_evaluated', models.IntegerField(default=0)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConceptVerdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pn_num', models.CharField(max_length=20)),
                ('case_num', models.IntegerField()),
                ('feature_num', models.CharField(max_length=10)),
                ('concept', models.CharField(max_length=200)),
                ('predicted', models.BooleanField()),
                ('ground_truth', models.BooleanField()),
                ('evidence', models.TextField(blank=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verdicts', to='assessment.evaluationrun')),
            ],
            options={
                'indexes': [models.Index(fields=['run', 'case_num'], name='assessment__run_id_79e3b2_idx'), models.Index(fields=['pn_num', 'feature_num'], name='assessment__pn_num_db4700_idx')],
            },
        ),
    ]
