# Generated by Django 6.0.6 on 2026-06-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationrun',
            name='case_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluationrun',
            name='note_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evaluationrun',
            name='student_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='evaluationrun',
            name='student_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
