# Generated by Django 6.0.6 on 2026-07-23 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_evaluationrun_user_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptverdict',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
